name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: cd sdks/python/friday-logger
      - run: pip install -r requirements.txt
      - run: echo ${{ github.sha }}
      - run: hatch version "$(hatch version).dev.${{ github.sha }}
