name: Publish Python Package
run-name: Python New Package Version
on:
  push:
    paths:
      - sdks/python/friday-logger/**
    branches:
      - main
  workflow_dispatch: {}

jobs:
  publish-python-push:
    environment: production
    runs-on: ubuntu-latest
    needs: [
      format-python-sdk,
      linting-python-sdk,
      tests-python-sdk
    ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install python requirements
        run: pip install -r requirements.txt
        working-directory: sdks/python/friday-logger

      - name: Hatch Build
        run: hatch build
        working-directory: sdks/python/friday-logger

      - name: Hatch Publish
        run: hatch publish -r main --no-prompt
        working-directory: sdks/python/friday-logger
        env:
          HATCH_INDEX_USER: ${{ secrets.HATCH_INDEX_USER }}
          HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}
