name: Run Tests
run-name: Run Tests
on:
  push: {}
  workflow_dispatch: {}

jobs:
  formatting-api:
    name: Formatting (API)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install ruff
      - run: ruff format --check .

  formatting-python-sdk:
    name: Formatting (Python SDK)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdks/python/friday-logger
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install ruff
      - run: ruff format --check .

  formatting-js-sdk:
    name: Formatting (JS SDK)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdks/js
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bunx prettier --check .

  linting-api:
    name: Linting (API)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install -r requirements.txt
      - run: ruff check .

  linting-python-sdk:
    name: Linting (Python SDK)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdks/python/friday-logger
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install -r requirements.txt
      - run: ruff check .

  linting-js-sdk:
    name: Linting (JS SDK)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdks/js
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        working-directory: ./tests
        run: ./run-tests.sh
